"""Interactive setup command for DevAssist.

Guides new users through configuring their MCP connections.
"""

import os
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm

console = Console()
app = typer.Typer(help="Setup and configure DevAssist.")


def get_env_file_path() -> Path:
    """Get the path to the .env file."""
    return Path.home() / ".devassist" / ".env"


def load_existing_config() -> dict[str, str]:
    """Load existing configuration from .env file."""
    env_file = get_env_file_path()
    config = {}
    
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    key = key.replace("export ", "").strip()
                    value = value.strip().strip('"').strip("'")
                    config[key] = value
    
    return config


def load_devassist_env_into_os() -> None:
    """Merge ~/.devassist/.env into os.environ.

    MCPRegistry and LLM clients read credentials from the environment. The setup
    wizard persists them to ~/.devassist/.env only; without this step, ``devassist
    chat`` / ``devassist ask`` would see empty tokens even after a successful setup.

    Values already set in the process environment are not overwritten.
    """
    config = load_existing_config()
    for key, value in config.items():
        if value and not os.environ.get(key):
            os.environ[key] = value


def save_config(config: dict[str, str]) -> None:
    """Save configuration to .env file."""
    env_file = get_env_file_path()
    env_file.parent.mkdir(parents=True, exist_ok=True)
    
    lines = [
        "# DevAssist Configuration",
        "# Generated by 'devassist setup'",
        "",
    ]
    
    # Group by category
    categories = {
        "Claude on Vertex AI (Red Hat)": [
            "CLAUDE_CODE_USE_VERTEX",
            "CLOUD_ML_REGION", 
            "ANTHROPIC_VERTEX_PROJECT_ID",
        ],
        "GitHub": ["GITHUB_PERSONAL_ACCESS_TOKEN"],
        "Atlassian (Jira/Confluence)": [
            "ATLASSIAN_BASE_URL",
            "ATLASSIAN_EMAIL",
            "ATLASSIAN_API_TOKEN",
        ],
    }
    
    for category, keys in categories.items():
        has_values = any(config.get(k) for k in keys)
        if has_values:
            lines.append(f"# {category}")
            for key in keys:
                if config.get(key):
                    lines.append(f'export {key}="{config[key]}"')
            lines.append("")
    
    # Add any other keys not in categories
    known_keys = set()
    for keys in categories.values():
        known_keys.update(keys)
    
    other_keys = [k for k in config if k not in known_keys and config[k]]
    if other_keys:
        lines.append("# Other")
        for key in other_keys:
            lines.append(f'export {key}="{config[key]}"')
    
    with open(env_file, "w") as f:
        f.write("\n".join(lines))

    try:
        os.chmod(env_file, 0o600)
    except OSError:
        # Windows or filesystems without POSIX mode bits
        pass


@app.command()
def init():
    """Interactive setup wizard for DevAssist.
    
    Guides you through configuring:
    - Claude AI (via Red Hat Vertex AI)
    - GitHub integration
    - Atlassian (Jira Cloud / Confluence)
    """
    console.print(Panel.fit(
        "[bold blue]🚀 DevAssist Setup Wizard[/bold blue]\n\n"
        "This will help you configure DevAssist to connect to your developer tools.",
        border_style="blue"
    ))
    
    config = load_existing_config()
    
    # === Claude on Vertex AI (Red Hat) ===
    console.print("\n[bold cyan]1. Claude AI Configuration (Red Hat Vertex AI)[/bold cyan]")
    console.print("   Red Hat employees use Claude via Google Vertex AI.\n")
    
    if Confirm.ask("   Are you a Red Hat employee using Claude via Vertex AI?", default=True):
        config["CLAUDE_CODE_USE_VERTEX"] = "1"
        config["CLOUD_ML_REGION"] = "us-east5"
        
        current_project = config.get("ANTHROPIC_VERTEX_PROJECT_ID", "")
        project_id = Prompt.ask(
            "   Enter your GCP Project ID",
            default=current_project or "itpc-gcp-ai-eng-claude"
        )
        config["ANTHROPIC_VERTEX_PROJECT_ID"] = project_id
        
        console.print("   [green]✓[/green] Claude AI configured via Vertex AI")
        console.print("   [dim]Note: Run 'gcloud auth application-default login' if not already done.[/dim]")
    else:
        api_key = Prompt.ask(
            "   Enter your Anthropic API key",
            password=True,
            default=config.get("ANTHROPIC_API_KEY", "")
        )
        if api_key:
            config["ANTHROPIC_API_KEY"] = api_key
            config["CLAUDE_CODE_USE_VERTEX"] = "0"
            console.print("   [green]✓[/green] Claude AI configured via direct API")
    
    # === GitHub ===
    console.print("\n[bold cyan]2. GitHub Configuration[/bold cyan]")
    console.print("   Create a token at: https://github.com/settings/tokens")
    console.print("   Required scopes: repo, notifications, read:user\n")
    
    current_github = config.get("GITHUB_PERSONAL_ACCESS_TOKEN", "")
    if current_github:
        console.print(f"   [dim]Current token: {current_github[:10]}...{current_github[-4:]}[/dim]")
    
    if Confirm.ask("   Configure GitHub?", default=True):
        github_token = Prompt.ask(
            "   Enter your GitHub Personal Access Token",
            password=True,
            default=""
        )
        if github_token:
            config["GITHUB_PERSONAL_ACCESS_TOKEN"] = github_token
            console.print("   [green]✓[/green] GitHub configured")
        elif current_github:
            console.print("   [green]✓[/green] Keeping existing GitHub token")
    
    # === Atlassian Rovo MCP (Jira Cloud/Confluence/Compass) ===
    console.print("\n[bold cyan]3. Atlassian Configuration (Jira Cloud/Confluence)[/bold cyan]")
    console.print("   Uses official Atlassian Rovo MCP Server with OAuth authentication.")
    console.print("   On first use, you'll authenticate via browser.\n")
    
    current_atlassian_url = config.get("ATLASSIAN_SITE_URL", "")
    
    if Confirm.ask("   Configure Atlassian (Jira/Confluence)?", default=True):
        atlassian_url = Prompt.ask(
            "   Enter your Atlassian site URL (e.g., https://redhat.atlassian.net/)",
            default=current_atlassian_url or "https://redhat.atlassian.net/"
        )
        # Ensure trailing slash for consistency
        if not atlassian_url.endswith("/"):
            atlassian_url += "/"
        config["ATLASSIAN_SITE_URL"] = atlassian_url
        console.print("   [green]✓[/green] Atlassian configured (OAuth - browser auth on first use)")
    
    # === Save Configuration ===
    console.print("\n[bold cyan]Saving configuration...[/bold cyan]")
    save_config(config)
    
    env_file = get_env_file_path()
    console.print(f"   [green]✓[/green] Configuration saved to: {env_file}")
    
    # === Summary ===
    if sys.platform == "win32":
        env_hint = (
            "Load these variables into your environment before running DevAssist "
            "(e.g. System Properties → Environment Variables, or your shell profile).\n"
            f"Config file: [dim]{env_file}[/dim]"
        )
    else:
        env_hint = (
            "To load in your shell:\n"
            f"  [cyan]source {env_file}[/cyan]\n\n"
            "Or add that line to your shell profile (e.g. ~/.bashrc or ~/.zshrc)."
        )

    console.print(Panel.fit(
        "[bold green]Setup Complete![/bold green]\n\n"
        f"{env_hint}\n\n"
        "Try:\n"
        '  [cyan]devassist ask "Give me a morning brief" -s atlassian,github[/cyan]\n'
        "Or:\n"
        "  [cyan]devassist chat -s atlassian,github[/cyan]",
        border_style="green",
    ))


@app.command()
def status():
    """Show current configuration status."""
    config = load_existing_config()
    
    console.print(Panel.fit(
        "[bold blue]DevAssist Configuration Status[/bold blue]",
        border_style="blue"
    ))
    
    checks = [
        ("Claude AI (Vertex)", config.get("CLAUDE_CODE_USE_VERTEX") == "1" and config.get("ANTHROPIC_VERTEX_PROJECT_ID")),
        ("Claude AI (Direct)", config.get("ANTHROPIC_API_KEY")),
        ("GitHub", config.get("GITHUB_PERSONAL_ACCESS_TOKEN")),
        ("Atlassian", config.get("ATLASSIAN_BASE_URL") and config.get("ATLASSIAN_EMAIL") and config.get("ATLASSIAN_API_TOKEN")),
    ]
    
    for name, configured in checks:
        status = "[green]✓ Configured[/green]" if configured else "[red]✗ Not configured[/red]"
        console.print(f"  {name}: {status}")
    
    env_file = get_env_file_path()
    console.print(f"\n  Config file: {env_file}")
    
    if not any(c[1] for c in checks):
        console.print("\n  [yellow]Run 'devassist setup init' to configure.[/yellow]")


def check_and_prompt_setup() -> bool:
    """Check if setup is needed and prompt user.
    
    Returns:
        True if setup is complete, False if user needs to run setup.
    """
    config = load_existing_config()
    
    # Check minimum requirements (Claude + at least one source)
    has_claude = (
        (config.get("CLAUDE_CODE_USE_VERTEX") == "1" and config.get("ANTHROPIC_VERTEX_PROJECT_ID"))
        or config.get("ANTHROPIC_API_KEY")
    )
    has_source = (
        config.get("GITHUB_PERSONAL_ACCESS_TOKEN")
        or (config.get("ATLASSIAN_BASE_URL") and config.get("ATLASSIAN_EMAIL") and config.get("ATLASSIAN_API_TOKEN"))
    )
    
    if has_claude and has_source:
        return True
    
    console.print(Panel.fit(
        "[yellow]⚠️  DevAssist is not configured yet.[/yellow]\n\n"
        "Run the setup wizard to configure your connections:\n"
        "  [cyan]devassist setup init[/cyan]",
        border_style="yellow"
    ))
    
    return False
